# sudo: true
language: go
go:
  - 1.6.2

before_install:
  # print go version
  - go version && go env
  - curl -sSL -o /tmp/ci_functions https://raw.githubusercontent.com/westmisfit/ci_functions/1.0.2/functions.sh; source /tmp/ci_functions
install:
  

script:
  - echo "begin"
  - go run command/main.go
  - echo "begin ping"
  - checkHealth "http://localhost:8082/ping"
  - echo "finished ping"

notifications:
  email:
    recipients:
      - michelia@fossil.com